### ISSUE TITLE
Maps: missing data in comparison histogram

### ISSUE THREAD

**Issue by Peter-Kraft** [episphere/epitracker#21]
The comparison histogram on the lower right: some counties display bars, some do not. For example, when looking at age-adjusted rates for stomach cancer compared by race, clicking on San Juan county in New Mexico yields no bars. Then if you click on Caddo county in Louisiana, you see a bar for Black people but no other group. Perhaps because (some of) the race-specific rates are missing? Hm. I wonder if there is some way to indicate that, to differentiate between out of range (super low or super high rates) and just plain missing.

**Comment by LKMason** [comment]
This is due to the data suppression, if there are fewer than 10 deaths we have to suppress the rates. I'm not sure if we have to be as strict about the age-adjusted rates (because it is harder to use them to work out exact death counts), but I think it's better to be cautious. 

I agree that the display is confusing. Perhaps we could grey out the ticks in the bar chart for groups with a suppressed value? And perhaps add a strike through. I'll have a think if there's a better way to handle this and we could all discuss it next meeting.

**Comment by LKMason** [comment]
I found an interesting discussion about this: https://ux.stackexchange.com/questions/69738/design-pattern-to-display-missing-data-in-line-bar-chart-of-a-daily-data-feed . I like the poster's approach with the color and the symbol (we could choose a symbol that indicate the data is missing/suppressed, perhaps a grey 'no' symbol (🚫 but grey!). I also like Veltri's approach with the big grey bar.

**Comment by Peter-Kraft** [comment]
Yesh something like either of these would be nice. I prefer the grey "no
data" bar. Also prefer grey "N/A' to grey "[no]."

**Comment by Sahar-behpour** [comment]
Working on it
