### ISSUE TITLE
Separate HTML from JS

### ISSUE THREAD

**Issue by bkop-ds** [episphere/epitracker#87]
There are odd things that are linked to the legacy reliance on the previous framework, like defining the HTML documents in JS files. We should discuss if this is necessary because if not I think we should put them into HTML documents.
Ex. See "About" page

**Comment by LKMason** [comment]
Agreed, I think this should be a priority so that the code can be clean going forward. I think we should structure the core of the application as follows:

* HTML pages as HTML documents. 
* No JS based routing, I don't think we need it (i.e. get rid of `epitracker.js`)
* Get rid of every file and bit of code that isn't related to EpiTracker.
